# Generated by Django 4.2.16 on 2024-09-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_author_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='outline',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='outline',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='concept',
            name='description',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='course',
            name='outline',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='session',
            name='outline',
            field=models.CharField(max_length=500),
        ),
    ]
