# Generated by Django 4.2.16 on 2024-09-13 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_course_created_at_alter_session_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.author'),
        ),
    ]
