# Generated by Django 4.2.16 on 2024-09-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_session_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='linkedInUrl',
        ),
        migrations.RemoveField(
            model_name='author',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='session',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='author',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
