# Generated by Django 4.2.16 on 2024-09-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_author_linkedin_url_alter_concept_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
