# Generated by Django 4.2.16 on 2024-10-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_concept_title_alter_session_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
