TEXT_CONSTRAINTS = {
    'SINGLE_NAME_LEN': 15,
    'TITLE_LEN': 50,
    'OUTLINE_LEN': 500,
    'SHORT_DESCRIPTION_LEN': 1500,
    'DESCRIPTION_LEN': 10000,
}

COURSE_CATEGORIES = [
    ('TECH', 'TECH'),
    ('HEALTH', 'HEALTH'),
    ('FINANCE', 'FINANCE'),
    ('LEADERSHIP', 'LEADERSHIP')
]